### ISSUE TITLE
command `conda install -c gilbertfrancois imutils` gives a never ending `Solving environment: \`

### ISSUE THREAD

**Issue by bjce** [jrosebr1/imutils#107]
Hello

First of all, thanks a lot for writing and maintaining the packages

I want to install `imutils` with `anaconda` and copied the command `conda install -c gilbertfrancois imutils` from [this website](https://anaconda.org/gilbertfrancois/imutils). I then get a `Solving environment: \` (as a spinning wheel), but it never ends? do you have any idea what could be the problem?

Specifications
- macOS 10.14
- Python 3.7.1

**Comment by bjce** [comment]
I did `pip install imutils`. I still don't understand why sometimes you have to install with `conda` sometimes with `pip`. That really gives a headache. But that obviously don't have anything to do with `imutils`. Thanks a lot again for writing and maintaining the package!

**Comment by Prestantious** [comment]
Conda is a way to manage your python packages so that they stay separate from the rest of your system and you can assure that you use the correct version for a specific program. Installing with pip, installs the package straight onto your machine, you need to be careful with this since it can mess up your dependencies.
