### ISSUE TITLE
imutils.resize returns not appropriate size

### ISSUE THREAD

**Issue by vvvin333** [jrosebr1/imutils#229]
When I resize jpg-files to (2000,2000,3) 
from (3932,3933,3) with imutils.resize(x,2000,2000) I have got this image with (1999,2000,3) shape!
But with cv2.resize(x, (2000,2000)) I have no such a problem.

**Comment by jhfdevelop** [comment]
Ok, just had the same problem and I think I figured it out:

The `imutils.resize` function is not really intended to take a width and a height argument simultaneously because the method preserves the aspect ratio. The idea is to specify one dimension as target and the other will be calculated. [The documentation](https://github.com/jrosebr1/imutils#resizing) and [the implementation](https://github.com/jrosebr1/imutils/blob/df65a77087548b5952431cc8006d66bcca7b1abc/imutils/convenience.py#L65) make that very clear. 

So if you want exact width and height dimensions you don't really need this function and you can call the `cv2.resize` function directly.
If you want to preserve the aspect ratio though, just don't specify the  dimension that you allow to change.

Also have a look at [this pr](https://github.com/jrosebr1/imutils/pull/110)

I hope this helps

**Comment by vvvin333** [comment]
Thnx for reference to implementation.
