### ISSUE TITLE
import imutils error in Debian

### ISSUE THREAD

**Issue by GingerMuda** [jrosebr1/imutils#7]
Hi Jrose,

I am trying to import imutils in Debian distro running on BeagleBone Black. This is what im getting when i import it in the Python Interpreter;
root@beaglebone:~# python
Python 2.7.3 (default, Mar 14 2014, 17:55:54) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import imutils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/imutils/__init__.py", line 5, in <module>
    from .convenience import translate
  File "/usr/local/lib/python2.7/dist-packages/imutils/convenience.py", line 108, in <module>
    def url_to_image(url, readFlag=cv2.IMREAD_COLOR):
AttributeError: 'module' object has no attribute 'IMREAD_COLOR'
>>> 

How can i rectify the problem?

**Comment by jrosebr1** [comment]
the `IMREAD_COLOR` is part of the `cv2` module which are your OpenCV bindings. Which OpenCV version are you using? I've seen errors like this happen when you install OpenCV via `apt-get` instead of compiling via source.

Run:

<pre>$ python
>>> import cv2
>>> cv2.__version___</pre>

And then report back your version.

**Comment by GingerMuda** [comment]
This is the kernel version i am operating on;
root@beaglebone:~# uname -a
Linux beaglebone 3.8.13-bone79 #1 SMP Tue Oct 13 20:44:55 UTC 2015 armv7l
GNU/Linux

See below for the cv2 version running on the system;

root@beaglebone:~# python
Python 2.7.3 (default, Mar 14 2014, 17:55:54)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'$Rev: 4557 $'
>>>

**Comment by jrosebr1** [comment]
It sounds like you installed OpenCV via `apt-get`, which normally installs an out-dated version with functionality missing. I would suggest installing OpenCV from source to avoid this issue. The instructions listed below can be used to install OpenCV from source for Debian:

http://www.pyimagesearch.com/2015/06/22/install-opencv-3-0-and-python-2-7-on-ubuntu/

I'm going to go ahead and close this issue now. Re-flash Debian onto your BeagleBone Black and then compile OpenCV from source and it should take care of the issue. Otherwise, it might be a BBB issue, and since I do not have one, I cannot further diagnose the problem.
